### PR TITLE
Jordan Freundlich

### PR DESCRIPTION
**Pull request by Jfreundlich01**

### CODE REVIEW

**Comment by SamiDenis** [comment]
Hey Jordan! Great job on the homework so far! Just a few thing to note:
#3 part 2: It's almost correct but not quite; the messages print but not for even numbers;
#4: The console.log(“i”) should not be in quotes. It ends up printing the letter "i" in the console, instead of numbers;
#7: Great job of removing the left shoe, but you also need to add the left shoe to Thom's accessories;
#8: The console prints  some of Kristyn’s closet, but there’s also an undefined. There’s a slight mistake made. You’re so close !

**Comment by SamiDenis** [comment]
Hey Jordan! Great job on the homework so far! Just a few thing to note:
Commit 3 part 2: It's almost correct but not quite; the messages print but not for even numbers;
Commit 4: The console.log(“i”) should not be in quotes. It ends up printing the letter "i" in the console, instead of numbers;
Commit 7,: Great job of removing the left shoe, but you also need to add the left shoe to Thom's accessories;
Commit 8: The console prints some of Kristyn’s closet, but there’s also an undefined. There’s a slight mistake made. You’re so close !

I'll close this assignment but be sure to correct your mistakes by EOD tomrrrow!
👍 You got this!

**Comment by Jfreundlich01** [comment]
Hi Sam! Thanks for catching all those. I believe the seoncd commit labeled "Commit 2 - get Even Answered" (there is two called that lol) is the second part of Excited Kitchen. I skipped that one and seemed to have miss labeled it when I came back to it at the end. Good lesson to learn haha. I'll re commit it with the correct label and then work on the rest!

**Comment by SamiDenis** [comment]
Oh thanks for letting me know Jordan! And no worries at all, keep up the good work! 🙌🏾

**Comment by Jfreundlich01** [comment]
Sorry just to clarify and understand git more. Is that confirmed, I can't
push if a repo is closed?

**Comment by Jfreundlich01** [comment]
Hi Sam! Thanks again for catching these. Looking back they are silly
mistakes. Gotta go slower and more carefully as I do the homework. I fixed
the issues and committed and pushed them all, but they aren't showing up in
the git repository. Is that because it is closed?

Thanks for all the help!!

**Pull request closed without merging**
