### PR TITLE
Did these Merge?? Jordan Freundlich

### PR DESCRIPTION
**Pull request by Jfreundlich01**

### CODE REVIEW

**Comment by SamiDenis** [comment]
Great job Jordan! Your so close! Commit 2 still prints multiple times but not for even numbers!

**Comment by Jfreundlich01** [comment]
Think I got it now!

**Comment by SamiDenis** [comment]
Amazing!! Thank you so much, Jordan! Everything looks correct! 😁

**Comment by Jfreundlich01** [comment]
Lets gooo! Thanks for sticking with me :)

**Pull request closed without merging**
